[build]
providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "cd backend && npm ci",      # Use install since no lock file
  "cd frontend && npm ci"           # Use ci where lock file exists
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"
