[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "cd backend && npm install",      # Use npm install here because there's no lock file
  "cd frontend && npm ci"           # Keep npm ci for frontend since it has a lock file
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"